#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the arrayManipulation function below.
def arrayManipulation(n, queries):
    temp=[0]*n
    for i in queries:
        temp[i[0]-1]+=i[2]
        if i[1]!=n:
            temp[i[1]]-=i[2]
    vmax=0
    msum=0
    for j in temp:
        msum+=j
        if msum>vmax:
            vmax=msum
    return(vmax)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
