#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#

def timeConversion(s):
    hour=int(s[:2])
    meridian=s[-2:]
    if meridian == "AM":
        hour = (hour+1) %12 -1
        return ("%02d" % hour) + s[2:-2]
    elif meridian == "PM":
        hour = hour %12 + 12
        return str(hour) + s[2:-2]

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
